// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jckwxuyhrbekioofytnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impja3d4dXlocmJla2lvb2Z5dG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzM3OTAsImV4cCI6MjA2MDM0OTc5MH0.fSpln0ypgVWN5jTacWFMJF8EAN8h8LV8IG9QMbevr6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);